export const kutaBeachDestinationSmall = require('./kuta_beach_small.png')

export const onboarding_1 = require('./onboarding_1.png')
export const onboarding_2 = require('./onboarding_2.png')
export const onboarding_3 = require('./onboarding_3.png')

// categories
export const category_beach = require('./categories/category_palm.png')
export const category_camping = require('./categories/category_camping.png')
export const category_fishing = require('./categories/category_fishing.png')
export const category_mountins = require('./categories/category_mountain.png')
export const category_forest = require('./categories/category_forest.png')
export const category_wave = require('./categories/category_wave.png')
// places
export const BanffNationalPark = require('./places/BanffNationalPark.jpg')
export const Bali = require('./places/Bali.jpg')
export const BoraBora = require('./places/Bora-Bora.jpg')
export const Etretat = require('./places/Etretat.jpg')
export const GreatBarrierReef = require('./places/GreatBarrierReef.jpg')
export const MachuPicchu = require('./places/MachuPicchu.jpg')
export const MountCook = require('./places/MountCook.jpg')
export const Santorini = require('./places/Santorini.jpg')
export const VictoriaFalls = require('./places/VictoriaFalls.jpg')
export const ArchitectureInBarcelonaSpain = require('./places/ArchitectureInBarcelona-Spain.jpeg')
export const EileanDonanLochDuichIslandScotland = require('./places/EileanDonan-LochDuichIslandScotland.jpeg')
export const GoldenGateBridgeSanFranciscoUSA = require('./places/GoldenGateBridge-SanFranciscoUSA.jpeg')
export const HorseshoeBendArizonaUSA = require('./places/HorseshoeBend-ArizonaUSA.jpeg')
export const LysefjordenNorway = require('./places/Lysefjorden-Norway.jpeg')
export const MilfordSoundNewZeland = require('./places/MilfordSound-NewZeland.jpeg')
export const MoraineLakeCanada = require('./places/MoraineLake-Canada.jpeg')
export const MunichGermany = require('./places/Munich-Germany.jpeg')
export const TheEiffelTowerParisFrance = require('./places/TheEiffelTower-ParisFrance.jpeg')

export const SmallBooking1 = require('./small_booking1.png')
export const SmallBooking2 = require('./small_booking2.png')
export const SmallBooking3 = require('./small_booking3.png')
