export {default as ColorPalleteView} from './ColorPalleteView'
export {default as TypographyView} from './TypographyView'
export {default as ButtonView} from './ButtonView'
export {default as Rate} from './Rate'

export {default as Button} from './Button'
export {default as Category} from './Category'
export {default as Package} from './Package'
export {default as Destination} from './Destination'
export {default as Input} from './Input'
export {default as Switch} from './Switch'
export {default as Header} from './Header'
export {default as ScreenTitle} from './ScreenTitle'

export {default as Text} from './Text'
export {default as Heart} from './Heart'
